services:
  - type: web
    name: diabetes-predict
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn diabetes_web.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: diabetes-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: MODEL_STRICT_MODE
        value: "True"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.mailgun.org"
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_USE_TLS
        value: "False"
      - key: EMAIL_USE_SSL
        value: "True"
      - key: EMAIL_HOST_USER
        value: "dbp@sandbox0f8ba03a66144746879546f692acd231.mailgun.org"
      - key: EMAIL_HOST_PASSWORD
        value: "Happylife@15"
      - key: DEFAULT_FROM_EMAIL
        value: "g0300747@gmail.com"

databases:
  - name: diabetes-db
    databaseName: diabetes
    plan: free
